name: push

on:
  - push

jobs:
  push:
    name: push

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: install packages
        run: dotnet restore 

      - name: build
        run: dotnet build

      - name: test
        run: dotnet test